#!/bin/bash

# set this to desired output
if [ "$1" = "-h" ]
then
    echo "Usage: [customer] [task] [seconds]";
else
	#set this to deired output
        destdir=/home/martin/Desktop/work_log.txt
        duration=$3

        echo "... tracking you time: " ;
        for i in `seq $3 -1 1` ; do echo -ne "\r$i " ; echo "" ; sleep 1 ; done

        echo $(date +"%x %X:") $@ >> "$destdir"
fi
